services:
  _defaults:
    public: false
    autowire: true

  PrestaShop\Module\APIResources\List\ModuleQueryBuilder:
    parent: 'prestashop.core.grid.abstract_query_builder'
    autowire: true

  prestashop.core.grid.data_factory.hook:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    public: true
    arguments:
      - '@prestashop.core.api.query_builder.hook'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'hook'

  prestashop.core.grid.data_factory.module:
    class: PrestaShop\Module\APIResources\List\ModuleGridDataFactory
    public: true
    arguments:
      - '@PrestaShop\Module\APIResources\List\ModuleQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'module'

  PrestaShop\Module\APIResources\Validation\IframeValidationGroupsResolver:
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  PrestaShop\Module\APIResources\Command\GenerateApiTrackingTableCommand:
    tags:
      - { name: 'console.command' }

  # Custom normalizers for commands/queries that are very specific and cannot rely on generic solutions from the core
  PrestaShop\Module\APIResources\ApiPlatform\Normalizer\GenerateCombinationsSerializer:
    autowire: true
    autoconfigure: true
    public: false

  PrestaShop\Module\APIResources\ApiPlatform\Normalizer\StateIdInterfaceNormalizer:
    tags:
      - { name: 'serializer.normalizer', priority: 100 }

  PrestaShop\Module\APIResources\ApiPlatform\Normalizer\CountryIdNormalizer:
    tags:
      - { name: 'serializer.normalizer', priority: 100 }

  PrestaShop\Module\APIResources\ApiPlatform\Normalizer\CartAddressNormalizer:
    autowire: true
    public: false
    arguments:
      $decorated: '@serializer.normalizer.object'
    tags:
      - { name: 'serializer.normalizer', priority: 300 }

  PrestaShop\Module\APIResources\ApiPlatform\Normalizer\OrderAddressNormalizer:
    autowire: true
    public: false
    arguments:
      $decorated: '@serializer.normalizer.object'

  PrestaShopBundle\ApiPlatform\Serializer\CQRSApiSerializer:
    class: PrestaShop\Module\APIResources\Serializer\QueryParameterTypeCastSerializer
    decorates: 'api_platform.serializer'
    autowire: true
    arguments:
      $decorated: '@.inner'

  PrestaShop\Module\APIResources\ApiPlatform\Processor\BulkCustomersDeleteProcessor:
    tags:
      - { name: 'api_platform.state_processor' }
    arguments:
      $commandProcessor: '@PrestaShopBundle\ApiPlatform\Processor\CommandProcessor'

  PrestaShop\Module\APIResources\ApiPlatform\Normalizer\BulkDeleteCustomerCommandDenormalizer:
    tags:
      - { name: 'serializer.normalizer', priority: 100 }
    arguments:
      $denormalizer: '@PrestaShopBundle\ApiPlatform\Normalizer\CQRSApiNormalizer'
