name: Build release
on: [push, pull_request]

jobs:
  build-and-release-draft:
    uses: PrestaShop/.github/.github/workflows/build-release.yml@master
    with:
      autoindex_excluded_folders: src/ApiPlatform/Resources
